apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: sail-operator
    app.kubernetes.io/created-by: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.deployment.name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: {{ .Values.name }}
    control-plane: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      control-plane: {{ .Values.deployment.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow any source to access metrics from RH Network Policy Recommendations Doc
    - ports:
        - protocol: TCP
          port: 8443

  egress:
    # Allow egress to API Server from RH Network Policy Recommendations Doc
    - ports:
        - protocol: TCP
          port: 6443

    {{- if eq .Values.platform "openshift" }}
    # OpenShift DNS access from RH Network Policy Recommendations Doc
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
          podSelector:
            matchLabels:
              dns.operator.openshift.io/daemonset-dns: default
      ports:
        - protocol: TCP
          port: dns-tcp
        - protocol: UDP
          port: dns
    {{- else if eq .Values.platform "kubernetes" }}
    # Kubernetes DNS access
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    {{- end }}

  